title : Codingforever 
tagline: Blog Tagline
author :
  name : zhujiefirst
  email : zhujiefirst@gmail.com
  github : zhujiefirst
  twitter : zhujiefirst@gmail.com
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - about.md
  
